name: Notify Discord on Commit

on:
  push:
    branches:
      - "*"

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          REPO_URL: https://github.com/${{ github.repository }}
        run: |
          # Extract commit details
          COMMIT_AUTHOR=$(echo '${{ toJson(github.event) }}' | jq -r '.head_commit.author.username')
          COMMIT_URL="$REPO_URL/commit/${{ github.sha }}"
          BRANCH_NAME="${{ github.ref_name }}"

          # Create JSON payload
          JSON_PAYLOAD=$(cat <<EOF
          {
            "content": "🚀 A new update has been pushed to **${{ github.repository }}** on branch **${BRANCH_NAME}**\n\n**Author**: ${COMMIT_AUTHOR}\n[View Commit](${COMMIT_URL})"
          }
          EOF
          )

          # Send the message to Discord
          curl -X POST \
          -H "Content-Type: application/json" \
          -d "$JSON_PAYLOAD" \
          $DISCORD_WEBHOOK_URL
